name: Publish Code Metrics
description: For rate of production analysis, this action calculates code metrics on the repo and pushes the results to S3.

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    - name: Generate Logical Complexity Metrics
      id: metrics
      uses: offgriddev/cyclomatic-js-action@main
      with:
        github_token: ${{ github.token }}
        event: ${{ toJson(github.event) }}
        excludedFileTypes: __mocks__|.test.js|Test.js|dist
        includedFileTypes: .js$

    - name: Upload Report
      uses: actions/upload-artifact@v3
      with:
        name: compreports
        path: complexity-assessment