name: Publish Code Metrics
description: For rate of production analysis, this action calculates code metrics on the repo and pushes the results to S3.

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    - name: Generate Terraform Metrics
      id: metrics
      uses: offgriddev/tf-metrics-action@main
      with:
        github_token: ${{ github.token }}
        event: ${{ toJson(github.event) }}

    - name: Upload Report
      uses: actions/upload-artifact@v3
      with:
        name: tfreports
        path: complexity-assessment
