name: Publish Code Metrics
description: For rate of production analysis, this action calculates code metrics on the repo and pushes the results to S3.
inputs:
  aws-access-key-id:
    required: true
  aws-secret-access-key:
    required: true
  environment:
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    - name: Download turbo artifact
      uses: actions/download-artifact@v3
      with:
        name: tfreports
        path: complexity-assessment

    - name: Download turbo artifact
      uses: actions/download-artifact@v3
      with:
        name: compreports
        path: complexity-assessment

    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: us-east-1
    
    - name: Publish Commit Analytics
      id: publish
      shell: bash
      run: |
        aws s3 sync complexity-assessment s3://${{ inputs.s3_bucket_name }} --cache-control max-age=31536000
