name: Complexity Analysis
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      s3-bucket-name:
        required: true
        type: string
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true

jobs:
  complexity-metrics:
    runs-on: ubuntu-20.04
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v3

      - name: Gather Complexity Metrics
        uses: ./.github/actions/complexity-metrics
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          environment: ${{ inputs.environment }}

  terraform-metrics:
    runs-on: ubuntu-20.04
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v3

      - name: Gather Terraform Metrics
        uses: ./.github/actions/terraform-metrics
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          environment: ${{ inputs.environment }}
  
  publish-to-s3:
    runs-on: ubuntu-20.04
    needs: ['complexity-metrics', 'terraform-metrics']
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v3

      - name: Publish Metrics to S3
        uses: ./.github/actions/publish-to-s3
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          environment: ${{ inputs.environment }} 
          s3-bucket-name: ${{ inputs.s3-bucket-name }}